language: go

matrixc:
  include:
  - go: "1.10.x"
  - go: "1.11.x"

before_install:
  - go get -u github.com/kardianos/govendor
  - govendor sync

env:
  - GO11MODULE=on

install: true

script:
  - go test -v -race ./... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)