language: go

matrixc:
  include:
  - go: "1.10.x"
    script: go test -v ./... -coverprofile=coverage.txt -covermode=atomic
  - go: "1.11.x"
    script: go test -v -mod=vendor ./... -coverprofile=coverage.txt -covermode=atomic

before_install:
  - go get -u github.com/kardianos/govendor
  - govendor sync

env:
  - GO11MODULE=on

install: true

after_success:
  - bash <(curl -s https://codecov.io/bash)