baseUrl = "customersApi"

[http]
port = 5001
useTLS = false
certFile = ""
keyFile = ""

[endpoints]

    [endpoints.getCustomers]
    path = "customers/:id/balances"
    file = "customers.json"
    method = "GET"

    [endpoints.getAccounts]
    path = "accounts"
    file = "accounts.json"
    method = "GET"

    [endpoints.getCustomerItems]
    path = "customers/:id/items"
    file = "items.json"
    method = "GET"