baseUrl = "customersApi"

[http]
port = 5001
useTLS = false
certFile = ""
keyFile = ""

[endpoints]

    [endpoints.getCustomers]
    path = "getCustomers/:id/funky"
    file = "customers.json"

    [endpoints.getAccounts]
    path = "getAccounts"
    file = "accounts.json"