baseUrl = "customersApi"
port = 5001

[endpoints]

    [endpoints.getCustomers]
    path = "getCustomers/:id/funky"
    file = "customers.json"

    [endpoints.getAccounts]
    path = "getAccounts"
    file = "accounts.json"