baseUrl = "studentsApi/:districtNumber"

[log]
loggingEnabled = false
fileName = "testLogs/studentsApi/default.log"
maxFileDaysAge = 3
formatAsJSON = true
prettyJSON = true

[http]
port = 5002
useTLS = false
certFile = ""
keyFile = ""

[endpoints]

    [endpoints.getStudents]
    path = "students"
    file = "students.json"
    method = "GET"

    [endpoints.getNothing]
    path = ""
    file = "students.json"
    method = "GET"

    [endpoints.postStudents]
    path = "students"
    file = "studentsPost.json"
    method = "POST"

    [endpoints.getGrades]
    path = "grades"
    file = "grades.json"
    method = "GET"