baseUrl = "studentsApi"
port = 5002

[endpoints]

    [endpoints.getStudents]
    path = "getStudents"
    file = "students.json"

    [endpoints.getGrades]
    path = "getGrades"
    file = "grades.json"