baseUrl = "studentsApi"

[http]
port = 5002
useTLS = false
certFile = ""
keyFile = ""

[endpoints]

    [endpoints.getStudents]
    path = "getStudents"
    file = "students.json"

    [endpoints.getGrades]
    path = "getGrades"
    file = "grades.json"