baseUrl = "studentsApi/:districtNumber"

[log]
loggingEnabled = true
fileName = "testLogs/studentsApi/default.log"
maxFileDaysAge = 3
formatAsJSON = true
prettyJSON = true

[http]
port = 5002
useTLS = false
certFile = ""
keyFile = ""

[endpoints]

    [endpoints.getStudents]
    path = "students"
    method = "GET"
    allowCORS = true
    HTTPStatusCode = 201

    [endpoints.getNothing]
    path = ""
    file = "students.json"
    method = "GET"
    enforceValidJSON = true
    allowCORS = true

    [endpoints.postStudents]
    path = "students"
    file = "studentsPost.json"
    method = "POST"

    [endpoints.getGrades]
    path = ":id/:test/"
    file = "grades.json"
    method = "GET"