baseUrl = "customersApi"

[log]
loggingEnabled = true
fileName = "testLogs/customersApi/default.log"
maxFileDaysAge = 3
formatAsJSON = true
prettyJSON = true

[http]
port = 5001
useTLS = false
certFile = ""
keyFile = ""

[endpoints]

    [endpoints.getCustomers]
    path = "customers/:id/balances"
    file = "customers.json"
    method = "GET"
    allowCORS = true

        [[endpoints.getCustomers.headers]]
        key = "content-type"
        value = "application/json; charset=utf-8"

    [endpoints.getAccounts]
    path = "accounts"
    file = "accounts.json"
    method = "GET"

    [endpoints.getNothing]
    path = ""
    file = "accounts.json"
    method = "GET"

    [endpoints.getCustomerItems]
    path = "customers/:id/items"
    file = "items.json"
    method = "GET"